@startuml 4d
start
:Nhập chuỗi ký tự;
if (chuỗi rỗng?) then (Yes)
:In thông báo "Chuỗi rỗng!";
stop
else (No)
:Set maxLength = 1;
:Set maxSubstring = chuỗi[0];
:Set i = 0; 
:Set j = length of chuỗi - 1;
while (i < length of chuỗi) is (Yes)
    :Set k = i;
    :Set l = j;
    while (k <= l?) is (Yes)
        if (isPalindrome(chuỗi[k, l])) then (Yes)
            :Cập nhật maxLength và maxSubstring;
        endif
        : k += 1,  l -= 1;
    endwhile (No)
    : i += 1;
endwhile (No)
:In ra dãy con đối xứng dài nhất;
stop
@enduml