@startuml 1c
start
:Nhập số nguyên dương n;
if (n < 1 or n >= 1000?) then (Yes)
:In thông báo lỗi: "n phải là số nguyên dương nhỏ hơn 1000";
stop
else (No)
:Set total = 0;
while (n > 0?) is (Yes)
:Set digit = n % 10;
:total = total + digit;
:n = Math.floor(n / 10);
endwhile (No)
:In tổng các chữ số total;
stop
@enduml
