
@startuml 9a
start
:Nhập chuỗi ký tự hoặc dãy số string;
:Nhập type (increase hoặc decrease);
:Khởi tạo biến maxLength = 1;
:Khởi tạo biến currentLength = 1;
:Khởi tạo biến startIndex = 0;
:Khởi tạo biến maxSubsequence = '';
:Khởi tạo biến i = 1;
while (i < string.length) is (Yes)
    if (type == "increase") then (Yes)
        if (string[i] > string[i - 1]) then (Yes)
            :currentLength++;
        else (No)
            if (currentLength > maxLength) then (Yes)
                :maxLength = currentLength;
                :maxSubsequence = string.substring(i - currentLength, currentLength);
            endif
            :currentLength = 1;
        endif
    else (No)
        if (string[i] < string[i - 1]) then (Yes)
            :currentLength++;
        else (No)
            if (currentLength > maxLength) then (Yes)
                :maxLength = currentLength;
                :maxSubsequence = string.substring(i - currentLength, currentLength);
            endif
            :currentLength = 1;
        endif
    endif
    : i += 1;
endwhile (No)
:In ra dãy con dài nhất: maxSubsequence;
stop
@enduml
