@startuml 9b
start
:Nhập chuỗi ký tự string;
:Nhập type (incresase hoặc decrease);
:let array = string.split('');
:Khởi tạo biến i = 0;
while (i < string.length) is (Yes)
    :Khởi tạo biến minMaxIndex = i;
    :Khởi tạo biến j = i + 1;
    while (j < string.length) is (Yes)
        if (type == "incresase") then (Yes)
            if (string[j] < string[minMaxIndex]) then (Yes)
                :minMaxIndex = j;
            endif
        else (No)
            if (string[j] > string[minMaxIndex]) then (Yes)
                :minMaxIndex = j;
            endif
        endif
        : j += 1;
    endwhile (No)
    :let temp = array[i];
    :array[i] = array[minMaxIndex];
    :array[minMaxIndex] = temp;
    : i += 1;
endwhile (No)
:In ra chuỗi đã sắp xếp array.join('');
stop
@enduml
