@startuml 6a
start
:Nhập số nguyên dương n;
if (n <= 0) then (Yes)
    :In thông báo "n phải là số nguyên dương!";
    stop
else (No)
    :Khởi tạo biến result = 1;
    :Set i = 1;
    while (i <= n) is (Yes)
        :result = result * i;
        : i += 1;
    endwhile (No)
    :In ra kết quả giai thừa của n: result;
    stop
end
@enduml
